
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ens-page
  namespace: ens-page
  annotations:
    cert-manager.io/cluster-issuer: le-http
spec:
  ingressClassName: traefik
  rules:
    - host: ens.page
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ens-page
                port:
                  number: 3000
  tls:
    - hosts:
        - ens.page
      secretName: tls-ens-page-ingress-http
