apiVersion: v1
kind: Service
metadata:
  name: ens-page
  namespace: default
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    run: ens-page
  type: ClusterIP
